### ISSUE TITLE
Connection template implementation

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#10]
As we know, OneView has a dedicated endpoint for Connection templates that are used by the Ethernet networks.

So, after some research I concluded that we could implement in Chef 2 actions for it, one is `update` and the other one is `reset_to_default`.

Although being that simple the names/URI for the Connection templates is not available to the end-user, it needs to be acquired through the Ethernet network name.

So my question is:  It makes more sense to create a separate Chef resource for the Connection template or add these 2 actions in the Ethernet network resource?

**Comment by hdiomede** [comment]
I would implement it on Ethernet network
