### ISSUE TITLE
Coverage for resource providers

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#102]
### Scenario/Intent
SimpleCov is complaining the resource providers aren't being tested by RSpec, but they are by the ChefSpec.

Should we remove them from the coverage report? Or should we migrate the tests to plain RSpec?

### Environment Details
 - **oneview Cookbook Version:** New (Post 1.0.0)

### Steps to Reproduce
`rake test`

### Expected Result
Coverage report should not be bellow expected

### Actual Result
Coverage report is failing due to low coverage

**Comment by jsmartt** [comment]
I saw that too, and I'm not sure. Will we want to test any of the specialized methods individually, or just try to cover them with chefspec? I think it would be good to test them with individual unit tests (much faster than the chefspec tests), but that's also an entirely new, big piece of work to add.

I was just going to keep them included for now and lower our coverage goals for the short term. But what do you think?

**Comment by tmiotto** [comment]
I would reaaly like to have them tested individually, alas we would still need the ChefSpec too... Since it's a great amount of work to do, and it won't add much more functionality (since ChefSpec is already testing them), just performance, I guess we should leave it as is.

Probably we would just remove the files from coverage report and leave an issue open for future improvements maybe.

**Comment by jsmartt** [comment]
The ChefSpec tests are taking longer and longer (currently around 3.5min 😴) , and it would be nice to speed them up. Testing the providers with pure rspec would certainly help a great deal, but I wonder if there are improvements we can make to ChefSpec as well. I found these 2 articles and at some point, I would like to dig in to see if the things mentioned within will help:
- https://github.com/sethvargo/chefspec#faster-specs
- https://github.com/PagerDuty/chef_example/blob/master/spec/spec_helper.rb#L40
- http://dracoater.blogspot.com/2013/12/testing-chef-cookbooks-part-25-speeding.html

**Comment by jsmartt** [comment]
Update on the ChefSpec speed-up: using `cached(:real_chef_run)` instead of `let(:real_chef_run)` broke a lot of tests, so that looks like a no-go. There may not be an easy way of speeding those up after all.

**Comment by yuvirani** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
