### ISSUE TITLE
API300::C7000::LogicalInterconnectGroupProvider logical_downlink & enclosure_index parameters

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-chef#150]
### Scenario/Intent
Add support for `logical_downlink` & `enclosure_index` parameters if/when the SDK [API::C7000::LogicalInterconnectGroup](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/resource/api300/c7000/logical_interconnect_group.rb) `#add_interconnect` method supports them. See [this note](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/resource_providers/api300/c7000/logical_interconnect_group_provider.rb#L19). Will need to update README when this happens also.

### Environment Details
 - **oneview Cookbook Version:** 1.1.0
 - **OneView Version:** API300::C7000

**Comment by yuvirani** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
