### ISSUE TITLE
Create ServerProfile from Template

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-chef#162]
### Scenario/Intent
I'd like to be able to define a `oneview_server_profile` resource that uses a ServerProfileTemplate as a base config (but allows me to override some of those settings with properties I set in addition). This would probably be done by adding a new `template` or `server_profile_template` property.

### Environment Details
 - **oneview Cookbook Version:** 1.1.0
 - **OneView Version:** 2.0 and 3.0

**Comment by tmiotto** [comment]
I guess it can be done using the `:new_profile`action with `oneview_server_profile_template` and then an `:create` with the custom values in with the `oneview_server_profile`.

Is your use case different from this one?

**Comment by jsmartt** [comment]
I didn't notice that action before. Yeah, basically the same use case, but I think it's pretty strange to have the `new_profile` action in the template resource. The real resource is the profile; we're just using the template. I think it's synonymous with the volume and volume_template resources, and should behave much more like that.
