### ISSUE TITLE
Show diff of resource that needs updated

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-chef#17]
When updating resources, there is no log output that indicates what is changed; just that it needs updated. However, when trying to debug a resource that continually needs updated because it seems to never match the definition, it's impossible to tell why.

For instance, if you have:

``` ruby
oneview_ethernet_network 'Chef-Eth-Net' do
  client <my_client>
  data(
    vlanId: 51,
    purpose: 'General',
    smartLink: true,
    privateNetwork: false
  )
end
```

It will always get "updated". On further investigation, it's because `"smartLink"=>false` on OneView, and it can't be set to false. It's pretty easy to output a diff for single-level hashes like ethernet_network data. You could just output:

``` bash
...
[2016-09-01T19:48:39+00:00] INFO: Update oneview_ethernet_network 'Chef-Eth-Net'

    - Update oneview_ethernet_network 'Chef-Eth-Net'

  key1: old_val -> new_val
  key2: old_val -> new_val
...
```

However, for nested hashes, this may prove a little more difficult. We could do a dot chain, which could look something like:

``` bash
...
[2016-09-01T19:48:39+00:00] INFO: Update oneview_ethernet_network 'Chef-Eth-Net'

    - Update oneview_ethernet_network 'Chef-Eth-Net'

  key1: old_val -> new_val
  first_level.key2: old_val -> new_val
  first_level.second.third.key3: old_val -> new_val
...
```

The easiest option would just be to print a debug statement with both complete hashes (no diff), but I think it's worth handling cleaner than that. Thoughts?

**Comment by tmiotto** [comment]
It would be an interesting feature to the cookbook.

I don't know if it would be trivial without editing the `like?` method from the Ruby SDK, but if you have any idea on how to implement it I totally agree adding it as a `Chef::log.debug` output.

**Comment by jsmartt** [comment]
I think I can come up with something... :wink:

**Comment by hdiomede** [comment]
That would be a nice feature!!!
