### ISSUE TITLE
Support SAS logical interconnect in API300

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#170]
### Scenario/Intent
Add support to SAS logical interconnect in API300.

### Environment Details
 - **oneview Cookbook Version:** 1.1.0
 - **OneView Version:** 300

**Comment by jsmartt** [comment]
This was added in #158 anything I missed?

**Comment by tmiotto** [comment]
#158 adds the SAS logical interconnect **group**

**Comment by jsmartt** [comment]
Ah! Thanks :)
