### ISSUE TITLE
Deprecate generic resource?

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#174]
### Scenario/Intent
The generic resource is still there, are we planning to deprecate/remove it?

Maybe it would also need an update, to comply with the providers if the decision is to mark it to deprecation or keep it onwards, and this need to be done before the completion of #173.

Any ideas @jsmartt ?

### Environment Details
 - **oneview Cookbook Version:** 1.1.0
 - **OneView Version:** API300

**Comment by jsmartt** [comment]
I think we should leave it in and just update it to use the new provider model. There are still plenty of OneView resources that we don't have custom resources for. Maybe we should remove the deprecation warning, because I see no reason to ever remove it.
