### ISSUE TITLE
Integration with Code Climate?

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#178]
### Scenario/Intent
Code Climate is a pretty cool and known cloud based tool to analyze our code quality, and since we have ruby code in our providers it would be a good to integrate it here.

The current oneview-chef status can be seen [here](https://codeclimate.com/github/HewlettPackard/oneview-chef).

Any oppositions, thoughts or suggestions?

**Comment by jsmartt** [comment]
I personally haven't found the site to be very useful, but if it's useful to you, go for it 😃

**Comment by tmiotto** [comment]
Well, I guess it is a good static analysis tool, if you know any better one we may go for it.

**Comment by jsmartt** [comment]
I think it's definitely the right choice for that sort of analysis. I was just saying I haven't ever really found the information that those sort of tools provide to be super helpful, personally, but I guess I haven't really given them a fair shot either. I'm perfectly fine with adding the badge; just might not look at it very often.

Were you just planning on putting a badge on the README, or integrating it into the CI pipeline as an additional validation?

**Comment by tmiotto** [comment]
Just putting a config yml and maybe adding the badge, the idea is more to open it regularly to see possible improvements and avoid the overall quality to drop too low.

**Comment by jsmartt** [comment]
Fixed by #190
