### ISSUE TITLE
Travis job for Ruby 2.1 is failing when is trying to install buff-extensions (2.0.0)

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#18]
Travis job for Ruby 2.1 is failing and outputting the following message:

> An error occurred while installing buff-extensions (2.0.0), and Bundler cannot continue.
> Make sure that `gem install buff-extensions -v '2.0.0'` succeeds before bundling.

**Comment by jsmartt** [comment]
I saw the same thing for the iLO cookbook, I just ended up removing 2.1 from the .travis.yml (and added 2.3.1 instead). It's not a direct dependency (berkshelf requires it), so I don't think that locking to a specific version in the Gemfile would be what we want to do. What do you guys think?

**Comment by tmiotto** [comment]
My opinion is if it's not a direct dependency of ours, so we do not need to lock the gem version. But, if we really want to support Ruby 2.1 and if it was caused by an Berkshelf gem update, we can lock the Berkshelf version.
