### ISSUE TITLE
Create Mixins for the resource providers common methods

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#180]
### Scenario/Intent
i'm seeing a lot of code that is common between one or more resources, but it won't make sense to use inheritance to avoid the code duplication, nor putting these methods in the main resource provider.

So I guess we could improve the code with Mixins implementing these common methods. having tests for them will also avoid implementing contless tests for the same feature.

### Environment Details
 - **oneview Cookbook Version:** 1.1.0-unreleased
 - **OneView Version:** API300

Actions to reuse:
- [x] `#reset`
- [x] `#set_power_state`
- [x] `#set_uid_light`
- [x] `#set_refresh_state`
- [ ] `#reapply_configuration`
- [ ] `#update_from_group`

**Comment by jsmartt** [comment]
Are there any specific methods or resource providers you would like to attach to this issue @tmiotto ?

**Comment by tmiotto** [comment]
Yes @jsmartt ,

There are `#reset`, `#set_power_state`, `#set_uid_light`, `#set_refresh_state`, `#reapply_configuration`, `#update_from_group`, that repeat all over the resources.

I will categorize them and list what kind of Mixins we should add to the cookbook.

:thought_balloon: : This actually may also apply to [HewlettPackard/oneview-sdk-ruby](https://github.com/HewlettPackard/oneview-sdk-ruby)

**Comment by yuvirani** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
