### ISSUE TITLE
Support development of unreleased features in Ruby SDK

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#184]
### Scenario/Intent
Make possible to develop features that weren't released yet in Ruby SDK without making the master unstable.

### Environment Details
 - **oneview Cookbook Version:** 1.2.0

**Comment by tmiotto** [comment]
By now I created a `master_i3s` branch to the new unreleased Image Streamer features.

**Comment by jsmartt** [comment]
@tmiotto , it's going to be a little tricky to run the tests on Travis with unreleased SDK features. I saw #185 that posed a solution to that, but it was closed. What about just updating the Gemfile of that branch to do something like this:
```
# Gemfile
...
gem 'oneview-sdk', :git => 'https://github.com/HewlettPackard/oneview-sdk-ruby.git', :branch => 'master'
...
```
(docs [here](http://bundler.io/git.html))
