### ISSUE TITLE
Add support to the Scopes resource

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-chef#187]
### Scenario/Intent
Use the scope resource that's been recently implemented in the oneview-ruby-sdk

### Environment Details
 - **oneview Cookbook Version:** 1.3.0
 - **OneView Version:** 3.0.0
 - **chef-client Version:** 12.18.31
 - **platform:** Windows 7

### Steps to Reproduce
Try to use the resource Scope through the oneview cookbook

### Expected Result
It should have the resource and be possible to use it

### Actual Result
This is currently not implemented.

**Comment by jsmartt** [comment]
@fgbulsoni , this looks very similar to #142. Can you combine any information that's needed and close one or the other?

**Comment by fgbulsoni** [comment]
> @fgbulsoni , this looks very similar to #142. Can you combine any information that's needed and close one or the other?

@jsmartt, it should be somewhat different. This issue regards the implementation for the actual resource called 'scope', while #142 refers to several different resources, which gained a 'scope' endpoint.

I could group those together, but it strikes me as just a naming resemblance in this case for two actually different things.

Would you still prefer to have these things coming as one issue?

**Comment by jsmartt** [comment]
Ah! Sorry, I didn't see that. No, this is fine
