### ISSUE TITLE
Standardize 'os_build_plan' properties

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#202]
### Scenario/Intent
We may want to standardize the use of 'os_build_plan' instead of only 'build_plan'.

Reason: Every piece of HPE OneView and Image Streamer refer it as 'OS Build Plan', although ruby implemented it `OneviewSDK::ImageStreamer::BuildPlan`

So, we may want to make the oneview cookbook use the right reference to it.

### Environment Details
 - **oneview Cookbook Version:** 2.1.0-unreleased

### Steps to Reproduce
Check Deployment Plan files.

### Expected Result
It should have the property `os_build_plan`

### Actual Result
It has the property `build_plan`

**Comment by jsmartt** [comment]
Sounds good to me
