### ISSUE TITLE
Improve OneviewSDK::ResourceProvider#load_resource to retrieve resources by other IDs than name

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#211]
### Scenario/Intent
I want to use the `OneviewSDK::ResourceProvider#load_resource` method to load resources by other unique IDs than `name`. Like connection templates by `uri` or Storage Pools by `name` and `hostname`.

### Environment Details
 - **oneview Cookbook Version:** 2.1.0
 - **OneView Version:** N/A
 - **Affects modules:** OneviewCookbook

### Steps to Reproduce
Try to retrieve a resource by URI, like loading the Connection Template in the EthernetNetworkProvider.

### Expected Result
I can load it using:
```ruby
connnection_template = load_resource(:ConnectionTemplate, uri: @item[:connectionTemplateUri])
```

### Actual Result
I need to load it by creating a new resource object, retrieving it, validating it exists, and raising an error if it don't, because I do not have the connection template name and load_resource does not accepts any other unique ID.

**Comment by jsmartt** [comment]
I like this. Maybe the method can still accept a string like before, and in that case we assume we want to search by name, but if you give a hash, it uses that directly instead.
