### ISSUE TITLE
Weird Enclosure retrieval in LogicalEnclosureProvider

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#214]
### Scenario/Intent
Why are [these attributes](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/resource_providers/api200/logical_enclosure_provider.rb#L31) being added there if a `retrieve!` is being performed?

None of those atttributes are unique IDs... can someone understand what this piece of code intended to do but couldn't?

### Environment Details
 - **oneview Cookbook Version:** 2.1.0

### Steps to Reproduce
See the [LogicalEnclosureProvider code](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/resource_providers/api200/logical_enclosure_provider.rb#L31).

### Expected Result
???

### Actual Result
Useless assignment of attributes

**Comment by jsmartt** [comment]
Those attributes are unique IDs ([see here](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/resource/api200/enclosure.rb#L21)). So it just allows the user to set any of them to do the retrieval.

**Comment by tmiotto** [comment]
Ooh, got it!

But... It's still a bit weird...

Also, looking at the code, something must be done in order to retrieve by key-tuples at the same time, like { name: 'CPG-OA', storageSystemName: 'ThreePar-1000' }
