### ISSUE TITLE
Support additional uplink port types in the LogicalInterconnectGroupProvider 

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-chef#225]
### Scenario/Intent
After [SDK issue #216](https://github.com/HewlettPackard/oneview-sdk-ruby/issues/216) gets implemented/fixed, we'll need to add the same support for our cookbooks.

Related resource:
- [api200/logical_interconnect_group_provider](https://github.com/HewlettPackard/oneview-chef/blob/v2.1.0/libraries/resource_providers/api200/logical_interconnect_group_provider.rb#L41)

### Environment Details
 - **oneview Cookbook Version:** 2.1.0
 - **OneView Version:** Synergy

### Expected Result
Support Q ports, etc., where we need to specify an enclosure_index to calculate the offset value.

### Actual Result
Not currently supported

**Comment by vranystepan** [comment]
I know that oneview-sdk with these enhancements ( HewlettPackard/oneview-sdk-ruby#230  ) needs to be released first but i will preliminary look at it ;)

**Comment by vranystepan** [comment]
Theoretically we can get interconnect module `type` from already loaded interconnects as they always have `type` and `bay` number and `enclosure_index`

1. compile some easily readable list from `@item.data['interconnectMapTemplate']['interconnectMapEntryTemplates']`
    - `['logicalLocation']['locationEntries'].find { |entry| entry['type'] == 'Bay' }`
    - `['logicalLocation']['locationEntries'].find { |entry| entry['type'] == 'Enclosure' }`
    - `['permittedInterconnectTypeUri']` (and fetch the type or name from OneView)
2. edit method load_uplink_sets so [this part](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/resource_providers/api200/logical_interconnect_group_provider.rb#L40) will be finding needed values in compiled structure

I can see a few challenges here ... for example these 16Gb Synergy FC switches and their `enclosure_index = -1` . I need to create some mockup and test in the real environment :)

**Comment by vranystepan** [comment]
Ahhh, I've just realized that API300::Synergy contains `@data['enclosureIndexes']` by default so we have to do following:

1. check whether `@item.data['enclosureIndexes']` exists (otherwise `enclosure_index` is `1` or `nil`, does not matter)
2. check the length of `@item.data['enclosureIndexes']`, when the length is 1 - `enclosure_index` will be `@item.data['enclosureIndexes'].first`
3. if length > 1 - uplinks connections info **has** to contain `enclosure_index`, example below

```ruby
uplink_connections = [
  { bay: 3, port: 'Q1', enclosure_index: 1 },
  { bay: 6, port: 'Q1', enclosure_index: 2 }
]
```

**Comment by vranystepan** [comment]
hmmm .... I can see how it has been solved in [Puppet library](https://github.com/HewlettPackard/oneview-puppet/blob/master/examples/logical_interconnect_group_synergy.pp#L40), that's actually great and straightforward solution. 

```ruby
parsed_uplink_info[:connections].each do |link|
  link[:type] ||= nil
  link[:enclosure_index] ||= 1
  up.add_uplink(link[:bay], link[:port], link[:type], link[:enclosure_index]) 
end
```

I will try to implement & test this week.
