### ISSUE TITLE
Add default PR comment

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-chef#25]
In order to help ensure good code and ensure PRs include all the expected things, it would be helpful to create a default comment for new PRs. (We can also do this for issues.) I saw this on the [rsyslog cookbook](https://github.com/chef-cookbooks/rsyslog/tree/master/.github), and the docs for how to do it are [here](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

Let's use this issue to discuss whether or not this is worth doing, and what the default should be.

**Comment by jsmartt** [comment]
I'll make a first pass:

### Description

[Describe what this change achieves]

### Issues Resolved

[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers_spec](../blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](../tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](../blob/master/CHANGELOG.md).

**Comment by hdiomede** [comment]
I liked it!!
