### ISSUE TITLE
Support for FC Network - API500

### ISSUE THREAD

**Issue by aalexmonteiro** [HewlettPackard/oneview-chef#251]
### Scenario/Intent
Add support to FC Network on the API500.

### Environment Details
 - **oneview Cookbook:** Version: 2.3.0
 - **OneView Version:** 3.10
 - **chef-client Version:** 12.0+
 - **platform:** Any

### Steps to Reproduce
Try to use the resource FC Network on the API 500.

### Expected Result
This resource supports API 500.

### Actual Result
This resource does not support API 500.

**Comment by tmiotto** [comment]
Please check #94
