### ISSUE TITLE
Add official support to Ruby 2.3 and 2.4

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#288]
### Scenario/Intent
We need to officially support Rubies 2.3 and 2.4.

It is needed to check the new best practices and deprecations and add these bew requirements to the cookbook. 

Until now the Travis CI is passing using ruby 2.3 and 2.4, so this probably means that will be needed just minor changes.

### Environment Details
 - **oneview Cookbook Version:** 2.3.0
 - **chef-client Version:** >= 12.21
 - **platform:** Ruby 2.3 and 2.4

**Comment by yuvirani** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
