### ISSUE TITLE
Add ID Pools IPv4 Subnets / Ranges resource

### ISSUE THREAD

**Issue by vranystepan** [HewlettPackard/oneview-chef#294]
### Scenario/Intent
I'd like to implement a new resource which will handle this Synergy-specific stuff. 

### API documentation
http://h17007.www1.hpe.com/docs/enterprise/servers/oneview3.0/cic-api/en/api-docs/current/index.html#rest/id-pools/ipv4/subnets

#### Sample subnet
```json
{
    "type" : "Subnet",
    "name" : "abc-subnet",
    "networkId" : "10.10.10.0",
    "subnetmask" : "255.255.255.0",
    "gateway" : "10.10.10.1",
    "domain" : "example.com",
    "dnsServers" : ["10.10.10.215"]
}
```

#### Sample Range
```json
{
    "type" : "Range",
    "name" : "IPv4",
    "rangeCategory" : "Custom",
    "startAddress" : "10.10.1.1",
    "endAddress" : "10:10.1.254",
    "subnetUri" : "/rest/id-pools/ipv4/subnets/daa36872-03b1-463b-aaf7-09d58b650142/"
}
```

#### Proposed structure of resource
```ruby
oneview_ipv4_subnet 'ManagementSubnet1' do
  network_id '192.168.255.0'
  subnet_mask '255.255.255.0'
  gateway '192.168.255.254'
  domain 'synergy.local'
  dns_servers ['4.4.4.4', '8.8.8.8']
  ip_ranges [
    {
      name: 'range1',
      start_address: '192.168.255.10',
      end_address: '192.168.255.100'
    },
    {
      name: 'range2',
      start_address: '192.168.255.100',
      end_address: '192.168.255.253'
    }
  ]
end
```

### Challenges
- Do we need to add support to oneview-sdk first? 
- Do we need separate oneview-sdk resource for `ID Pools IPv4 Ranges`?
- How to handle possible user changes in the Ranges (and/or Subnets)? What if user wants to change `name`?

**Comment by fgbulsoni** [comment]
> Do we need to add support to oneview-sdk first?

Yep, just verified and it doesn't seem like we have either of those implemented there.

> Do we need separate oneview-sdk resource for ID Pools IPv4 Ranges?

If we're following our standard procedure, yes, I'd imagine so.

> How to handle possible user changes in the Ranges (and/or Subnets)? What if user wants to change name?

In `chef` at least I don't think we support changing names. Confirm @tmiotto ?
In the ruby-sdk it'd likely be a normal update.

Also, we do have those implemented in ansible, perhaps taking a look there could help:
[ipv4 range example](https://github.com/HewlettPackard/oneview-ansible/blob/master/examples/oneview_id_pools_ipv4_range.yml) + [ipv4 subnet example](https://github.com/HewlettPackard/oneview-ansible/blob/master/examples/oneview_id_pools_ipv4_subnet.yml)

Feel free to contribute on the sdk+chef if you'd like though. :octocat:

**Comment by tmiotto** [comment]
> Do we need to add support to oneview-sdk first?
 - Yes, we do.
> Do we need separate oneview-sdk resource for ID Pools IPv4 Ranges?
 - Yes, it would work similar to the networks and Connection templates
> How to handle possible user changes in the Ranges (and/or Subnets)? What if user wants to change name?
  - Ranges and Subnets actually do not have name as unique identifier so I guess updating the name won't be a problem.
     - Subnets use the networkId as the id.
     - Ranges are bound to a subnet and must have a unique range.

**Comment by vranystepan** [comment]
So the first step would be support in oneview-sdk (`ID Pools IPv4 Ranges` + `ID Pools IPv4 Subnets`). Then we can add the same (separated) resources here and optionally add some _macro_ to the Subnets (similar to connection template in eth. networks). 

Ok, cool. I'm still a bit confused though but I don't have to resolve it now so I'm fine :smiley:

Thanks!

**Comment by yuvirani** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
