### ISSUE TITLE
Storage pool actions for API 500 are not working

### ISSUE THREAD

**Issue by ricardogpsf** [HewlettPackard/oneview-chef#340]
### Scenario/Intent
Running examples of StoragePool for API500 (examples/storage_pool_store_serv.rb), the actions of api500 (update, add_to_management, remove_from_management and refresh) throw errors, because some methods called by Oneview resource instance are not correct.

It is occuring 3 problems:

 1 - StoragePoolProvider of API500 is calling the `set_storage_system` method of OneviewSDK::API500::C7000::StoragePool through an instance of StoragePool, but method is not present in StoragePool of api500. This error occurs always when StorageSystem is loaded and the StorageSystem should be loaded for all actions.

 2 - StoragePoolProvider of API500 is calling the `manage` method of OneviewSDK::API500::C7000::StoragePool through an instance of StoragePool using a string as parameter, but the method expect a boolean parameter, so always when `add_to_management` and `remove_from_management` actions are called, the error is thrown. 
 
3 - The refresh action should load the StorageSystem before apply the action, otherwise the StoragePool is not found, but the refresh action is not loading the StorageSystem before. =(

For API200 and API300 all it is ok.

**Comment by fgbulsoni** [comment]
> Storage Pool provider for api500 is not working well

"Working well" is really vague and can mean a multitude of things, go with something direct like `Storage pool actions for API 500 causing failures` - or something similar. 
Also, since you've actually hit the actual errors, it's always best to include those in the Issue description.

**Comment by ricardogpsf** [comment]
@fgbulsoni Really the description and title were very vague. Thank you for that comment! =D
