### ISSUE TITLE
Add support for API version 600

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/oneview-chef#352]
### Scenario/Intent
[What you are trying to achieve but can't?]
Use API Version 600

### Environment Details
 - **oneview Cookbook Version:** [Version of this cookbook for which you are encountering the issue]
v 3.0.0
 - **OneView Version:** [Version of the OneView appliance you're interacting with]
4.0
 - **chef-client Version:** [Version of chef-client in your environment]
13.8.5
 - **platform:** [OS distribution and release version. Cloud provider if applicable]
Centos 7.4

### Steps to Reproduce
[If you are filing an issue, what are the things we need to do in order to reproduce your problem? How are you using this cookbook or any resources it includes?]
Attempting to set API version 600 as its requiring a match for this when attempting to set another version via the API Environment variables.

### Expected Result
[What do you *expect* to happen after taking the steps above?]
Expect API Version 600 to be available to be used.

### Actual Result
[What *actually* happens after the steps above? Include error output or a link to a gist.]
This does not work currently.

```
Recipe: atchef_oneview_frame001_bay003_dc1::default
  * oneview_server_profile_template[ServerProfileTemplate1] action create

    ================================================================================
    Error executing action `create` on resource 'oneview_server_profile_template[ServerProfileTemplate1]'
    ================================================================================

    ArgumentError
    -------------
    comparison of String with 600 failed

    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_provider.rb:38:in `new'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_provider.rb:38:in `initialize'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/oneview_helper.rb:46:in `new'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/oneview_helper.rb:46:in `do_resource_action'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/resources/server_profile_template.rb:29:in `block in class_from_file'```

```NameError
    ---------
    The api_version 600 is not supported in OneviewCookbook. Please use a supported version.

    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/oneview_helper.rb:81:in `rescue in get_api_module'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/oneview_helper.rb:78:in `get_api_module'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/oneview_helper.rb:69:in `get_resource_class'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/oneview_helper.rb:45:in `do_resource_action'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/resources/server_profile_template.rb:29:in `block in class_from_file'```

**Comment by soodpr** [comment]
@wingZero21 - We are working to provide support to API600 and soon we will release it. Are there any particular resources you are interested in?

**Comment by soodpr** [comment]
closing this issue as we are now supporting API600 for most of the resources in our latest release 3.1.0. Please see the [Changlelog.md](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md) file for the list of resources supported.
