### ISSUE TITLE
DEPRICATION Notice for the Fauxhai redhat platform 7.2

### ISSUE THREAD

**Issue by jjasghar** [HewlettPackard/oneview-chef#355]
Running yall's tests this pops up:
`.WARNING: Fauxhai platform data for redhat 7.2 is deprecated and will be removed in the 7.0 release 3/2019. A list of available platforms is available at https://github.com/chefspec/fauxhai/blob/master/PLATFORMS.md`

I can give it a shot, but this is probably an internal conversation that needs to happen. 

/cc @russellseymour @jsmartt

**Comment by jsmartt** [comment]
Thanks for the info JJ! We can sure bump that to 7.3 or 7.4

**Comment by jsmartt** [comment]
Fixed

**Comment by jjasghar** [comment]
yay!
