### ISSUE TITLE
Query on adding pre-existing network vlan to server profile

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/oneview-chef#391]
### Scenario/Intent
[What you are trying to achieve but can't?]

Is it possible to actually add an ethernet connection to the server profile without having it generated or existing from chef?

We have imported all the vlans through a script previously but now we just want to add the pre-existing networks and network sets onto the server profiles.

I am trying something similar to the below. Can you advise what connection name it would be looking for based on trying to add it from a network/vlan that has already been added to oneview. EG the name of the vlan that is in oneview is tf_a_hb_1888.

EG:
```ethernet_network_connections( tf_a_hb_1888: { "id": "1", "name": "connection1", "portId": "Mezzanine 3:1-c", "requestedMbps": "2500", "networkUri": "/rest/ethernet-networks/4caebc17-4e1d-45be-a500-eff1aade6524" })```

Error returned
```
EthernetNetwork with data '{:name=>:tf_a_hb_1888}' was not found
```

**Comment by jsmartt** [comment]
Hi @wingZero21, the network doesn't need to be defined anywhere in Chef; it just needs to exist in OneView. It uses that top level hash key (`tf_a_hb_1888`) to search for it on OneView by name, so just make sure that ethernet network exists in OneView by that exact name. It also needs to be an Ethernet network, not a FC or FCoE network; if it's another type, use the matching associated property name (e.g. `fc_network_connections`).

The hash value that your `tf_a_hb_1888` name key maps to is extra data that will override the connection object. As you have it, it will rename the connection in the profile to "connection1", set the portId, requestedMbps, and id. That's all fine. However, I'd recommend removing the `networkUri` property, as that doesn't assist in the search, and could cause some confusion later. If you change that but not the top level key `tf_a_hb_1888`, it probably won't do what you expect.

Let me know how it goes!

**Comment by wingZero21** [comment]
Hi,

This looks to have sorted it cheers!

**Comment by wingZero21** [comment]
@jsmartt another query related to this.

Is it possible to have multiple connections that are the same VLAN. It seems to be possible when configuring within the UI however when adding the same connection with a different ID, eg 2 it seems to just overwrite the prior one with the 2 ID rather than have one with ID 1 and 2.

Details:
```
ethernet_network_connections( "tf_a_hb_1888": { "id": "1", "name": "tf_a_hb_1888", "portId": "Auto", "requestedMbps": "2500", "networkUri": "/rest/ethernet-networks/4caebc17-4e1d-45be-a500-eff1aade6524" })
  ethernet_network_connections( "tf_a_hb_1888": { "id": "2", "name": "tf_a_hb_1888_2", "portId": "Auto", "requestedMbps": "2500", "networkUri": "/rest/ethernet-networks/4caebc17-4e1d-45be-a500-eff1aade6524" })
```

Managed to get it working by amending it from one of the other examples using [ instead of (.

**Comment by jsmartt** [comment]
Right. There's probably a few different syntaxes that would work. This is untested, but I think it should work:

```ruby
ethernet_network_connections(
  tf_a_hb_1888: { "id": "1", "name": "tf_a_hb_1888", "portId": "Auto", "requestedMbps": "2500" },
  tf_a_hb_1888: { "id": "2", "name": "tf_a_hb_1888_2", "portId": "Auto", "requestedMbps": "2500" }
)
```

I know you're familiar with Terraform, where you would define multiple `ethernet_network_connection` blocks. The syntax for Chef requires just one block, with multiple network definitions inside.

**Comment by wingZero21** [comment]
Hi,

Yeah I sorted it apologies I did update the comment to mention as I had to move it from [ to (.

Cheers
