### ISSUE TITLE
Document ServerProfile osDeploymentSettings

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-chef#392]
### Scenario/Intent
It looks like setting custom osDeploymentSettings is possible and made easier by some of the following code, but I can't find any documentation or examples of how to use it.

### Environment Details
 - **oneview Cookbook Version:** 3.1.0
 - **OneView Version:** all
 - **chef-client Version:** all
 - **platform:** all

### Steps to Reproduce
N/A

### Expected Result
N/A

### Actual Result
N/A

### Notes:
There are some tests that suggest the way it's done is:

```ruby
data('osDeploymentSettings' => { 'customAttributes' => [{ 'name' => 'your_key_name', 'value' => 'your_desired_value' }] })
```

See [here](https://github.com/HewlettPackard/oneview-chef/blob/0d6d42990fdae4ea467581ab5babad69fe08870d/spec/fixtures/cookbooks/oneview_test_api300_synergy/recipes/server_profile_properties.rb)

**Comment by yuvirani** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
