### ISSUE TITLE
Unkown type for ethernetSettings in LIG cookbook

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/oneview-chef#396]
### Scenario/Intent
Create a LIG with Ethernet Settings

### Environment Details
 - **oneview Cookbook Version:**  current version
 - **OneView Version:**  4.10
 - **chef-client Version:** 14.8.12
 - **platform:** Ubuntu 18.04

### Steps to Reproduce
The following cookbook creates a LIG with ethernetSettings. I use the api_version of 600 and according to the REST specs, the type is defined to ethernetInteconnectSettingsV4 ( This is also the value returned in a query of LIG)

my_client = {
    url: ENV['ONEVIEWSDK_URL'],
    user: ENV['ONEVIEWSDK_USER'],
    password: ENV['ONEVIEWSDK_PASSWORD'],
    api_version: 600
}

#---------------------------- Logical Interconnect Group LIG-ETH

  
oneview_logical_interconnect_group  "LIG ETH chef" do
     client my_client
     api_variant "Synergy" 
     data(
         redundancyType:         "redundant",
         enclosureIndexes:       [1],
         interconnectBaySet:     3,
         ethernetSettings: {
              type:                           "EthernetInterconnectSettingsV4",
              enableNetworkLoopProtection:   true, 
              enablePauseFloodProtection:     true 
          },
          enclosureType:              "SY12000"
         
     )
end

### Expected Result
Create a LIG with Ethernet settings

### Actual Result

FATAL: OneviewSDK::BadRequest: oneview_logical_interconnect_group[LIG ETH chef] (my_oneview::ov-test-lig line 37) had an error: OneviewSDK::BadRequest: 400 BAD REQUEST {"errorCode":"INVALID_JSON_DATA_TYPE","message":"Invalid JSON data type.","details":"The JSON sent in the request contained a unknown type where a different unknown type was required on line 1 near column 57.","recommendedActions":["Correct the content of the JSON and try the request again."],"errorSource":null,"nestedErrors":[],"data":{}}

**Comment by yuvirani** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
