### ISSUE TITLE
Support of using names of network in LIG internalNetworkURis

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/oneview-chef#397]
### Scenario/Intent
Support of using names of network in LIG internalNetworkURis

### Environment Details
 - **oneview Cookbook Version:** current version
 - **OneView Version:** 4.10
 - **chef-client Version:** 14.8.12
 - **platform:** Ubuntu 18.4

### Steps to Reproduce
When creating a LIG, a cookbook must support names for networks instead of Uris
Oneview-ansible SDK supports network names instead of URIs and renders cookbook much more portable

**Comment by yuvirani** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
