### ISSUE TITLE
Dockerfile is failing because of insufficient libraries

### ISSUE THREAD

**Issue by chebroluharika** [HewlettPackard/oneview-chef#419]
**Scenario/Intent**
Dockerfile is failing because of insufficient libraries

**Expected Result**
We should be able to build docker image successfully followed by running examples recipes in directory.

**Comment by soodpr** [comment]
Adding Docker logs error which was failing:
Step 4/16 : RUN chef gem install oneview-sdk --no-document # Ignore the warning about the path not containing gem executables
---> Running in 7159406b3f2d
Chef Development Kit cannot execute without accepting the license
Removing intermediate container 7159406b3f2d
The command '/bin/sh -c chef gem install oneview-sdk --no-document # Ignore the warning about the path not containing gem executables' returned a non-zero code: 172
