### ISSUE TITLE
Fix minimum Ruby lib dependency 

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#85]
### Scenario/Intent
Some dependencies require lower versions of Ruby and we need to manage them so Travis won't fail.

**Comment by jsmartt** [comment]
Btw, I've posted a [question on StackOverflow to see if there is an easy way to solve this](http://stackoverflow.com/questions/40348066/can-bundler-automatically-solve-ruby-version-dependencies). However, I think we're just going to have to keep adding version dependencies to our Gemfile until we decide not to test/support older Ruby versions.

**Comment by jsmartt** [comment]
I guess this poses the question whether or not we even should support older Ruby versions? We could just install chef-dk and let that decide which versions of dev tools to use. [This](https://github.com/chef-cookbooks/httpd/blob/master/.travis.yml#L10) is what Chef does for all the community cookbooks they manage.
